# Cloudflare Pages Configuration for AI Agent Platform
name = "ai-agent-platform"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Build configuration
[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

# Pages configuration
[pages]
build_output_dir = "dist"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Functions configuration for AI API routes
[[pages.functions]]
pattern = "/api/ai/*"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# Environment variables for development
[env.development]
[env.development.vars]
NODE_ENV = "development"
CF_PAGES = "1"
VITE_APP_ENVIRONMENT = "development"

# Environment variables for production
[env.production]
[env.production.vars]
NODE_ENV = "production" 
CF_PAGES = "1"
VITE_APP_ENVIRONMENT = "production"

# Preview configuration
[env.preview]
[env.preview.vars]
NODE_ENV = "development"
CF_PAGES = "1"
VITE_APP_ENVIRONMENT = "preview"